---
title: "Wk8"
author: "Gonzalo Banda-Cruz"
date: "8 March 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#Point pattern analyses
load the packages
```{r}
library(pacman)
pacman::p_load(tidyverse, sf, tmap, leaflet, spatstat, maptools)
```

##column groah of texas oil spills
```{r}
oilspills <- read_csv("oil_spills.csv")

df <- oilspills %>% 
  filter(`Accident State` == "TX" & `Accident Year` < 2017) %>% 
  group_by(`Accident Year`) %>% 
  summarise(Loss = sum(`Net Loss (Barrels)`))
#the inverted apostrophes are needed if there are spaces in the column names

colnames(df) <-  c("year", "loss")

ggplot(df, aes(x=year, y=loss))+
  geom_col()
```

#leaflet plot of spill locations tx in 2016
```{r}
df_loc <- oilspills %>% 
  filter(`Accident State`=="TX"& `Accident Year`==2016) %>% 
  select(Latitude, Longitude, `Net Loss (Barrels)`)

colnames(df_loc) <- c("latitude", "longitude", "net_loss")

#tell r the data is spatial 

oil_sf <- st_as_sf(df_loc, coords = c("longitude", "latitude"), crs = 4326)

leaflet(oil_sf) %>% 
  addTiles() %>% 
  addMarkers() 

```

## make a tmap plot with the TX shapefile
```{r}
#read the shpafile and indicate directory "."

states <- st_read(dsn = ".", layer = "states")

tex_border <- states %>% 
  filter(STATE_NAME == "Texas") %>% 
  st_transform(4326)

plot(tex_border)

tm_shape(tex_border)+
  tm_polygons()+
  tm_shape(oil_sf)+
  tm_dots(size = 0.3)

```
## convert the data to spatial point patterns (conbination of point data and the bounding window)

```{r}

spill_spatial <- as(oil_sf, "Spatial") #making sure r understands this is data for point pattern analyses

spill_ppp <- as(spill_spatial, "ppp")

tx_sp <- as(tex_border, "Spatial")
tx_owin <- as(tx_sp, "owin")

all_ppp <- ppp(spill_ppp$x, spill_ppp$y, window = tx_owin)

```

### density plot

```{r}

plot(density(all_ppp, sigma = 0.4))

```




